# Setup
title:               IDEEAS Lab
tagline:             'Website for IDEEAS'
description:         'Home of the IDEEAS Lab'
url:                 http://ideeaslab.github.io/
baseurl:             http://ideeaslab.github.io/
gems:                [jekyll-paginate, jekyll-gist]
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Andrew Katz
  url:               https://twitter.com/doc_katz
  email:             katz@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
